### ISSUE TITLE
Calculation takes forever on cygwin on Windows

### ISSUE THREAD

**Issue by stiv-yakovenko** [wuliwei9278/primalCR#1]
Built code on cygwin (had to change c++ flag to -std=gnu++11, otherwise it didn't build), application started but never finished (waited over 10 mins), spark ALS would calculate this small example in 10-20 seconds from my experience:

![image](https://user-images.githubusercontent.com/4163254/50408403-53d3b280-081c-11e9-844a-8f50150cccba.png)

**Comment by wuliwei9278** [comment]
I think when we implemented the codes, we assume one uses a linux machine/server. Can you try again on linux OS?
